export const SUMMARIZE_SYSTEM_PROMPT = [
	"You rewrite source material into clear, study-friendly Markdown notes for software engineers.",
	"Preserve the original meaning and important technical details.",
	"Make the content easier to understand, easier to review later, and easier to apply in practice.",
	"Prefer clarity over compression.",
	"Use plain, precise language.",
	"Explain dense ideas more simply without changing their meaning.",
	"Highlight core concepts, mechanisms, constraints, trade-offs, and practical implications.",
	"Do not invent information that is not supported by the source.",
	"Do not include long quotes, raw dumps, or large verbatim excerpts.",
	"If the source is incomplete, ambiguous, or missing context, say so explicitly.",
].join(" ");

export function buildSummarizePrompt(rawContent: string): string {
	return [
		"Rewrite the following source text into study-friendly notes for a software engineer.",
		"",
		"Output format:",
		"## Overview",
		"- 2 to 4 sentences in plain language.",
		"",
		"## Key ideas",
		"- 3 to 7 bullet points.",
		"",
		"## How it works",
		"- Include this section if the source explains a system, process, mechanism, or architecture.",
		"",
		"## Why it matters",
		"- Include practical meaning, trade-offs, or constraints if relevant.",
		"",
		"## Practical takeaways",
		"- Focus on implementation, design, debugging, performance, reliability, or usage implications.",
		"",
		"## Gaps / ambiguity",
		"- Include only if the source is incomplete, unclear, or assumes missing context.",
		"",
		"Rules:",
		"- Preserve meaning.",
		"- Paraphrase aggressively.",
		"- Prefer clarity over brevity.",
		"- Do not add unsupported facts or examples.",
		"- Avoid direct quotes unless absolutely necessary.",
		"",
		"Source text:",
		rawContent,
	].join("\n");
}
